version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nexus_admin
      - MONGO_INITDB_ROOT_PASSWORD=secure_password

  backend:
    build:
      context: ./nexus-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://nexus_admin:secure_password@mongodb:27017/nexus?authSource=admin
      - SPRING_DATA_MONGODB_DATABASE=nexus
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./nexus-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongodb_data: